
version: "3"
services:
  product:
    image: jessicamoraes/app-product
    build: product
    ports: 
      - 3001:3000
  
  account:
    image: jessicamoraes/app-account
    build: account
    volumes: 
    - ./account:/app

  account_db:
    image: mongo
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=jessica
      - MONGO_INITDB_ROOT_PASSWORD=123456789
    ports: 
      - 27017:27017

  product_db:
    image: mysql
    container_name: mysqldb
    environment:
      - MYSQL_DATABASE=products
      - MYSQL_ROOT_PASSWORD=root
    ports: 
      - 3307:3306



