version: "3"
services:
  product:
    depends_on:
      - mysqldb
    image: jessicamoraes/app-product
    build: product
    volumes:
    - ./product:/app
    ports:
    - 3001:3001

  mysqldb:
    image: mysql
    container_name: mysqldb
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_DATABASE=products
      - MYSQL_USER=jessica
      - MYSQL_PASSWORD=123456789
    ports:
    - 3306:3306

  account:
    depends_on:
      - mongodb
    image: jessicamoraes/app-account
    build: account
    entrypoint: 'npm run start:dev'
    volumes:
    - ./account:/app
    ports:
    - 3000:3000

  mongodb:
    image: mongo
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=jessica
      - MONGO_INITDB_ROOT_PASSWORD=123456789
    ports:
      - 27017:27017