
version: "3"
services:
  product:
    image: jessicamoraes/app-product
    build: product
  
  account:
    image: jessicamoraes/app-account
    build: account
    volumes: 
    - ./account:/app

  account_db:
    image: mongo
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=jessica
      - MONGO_INITDB_ROOT_PASSWORD=123456789
    ports: 
      - 27017:27017



