version: "3.9"
services:
  mongodb:
    image: mongo:4.4.6
    container_name: meu-mongo
    networks:
      - compose-bridge

  alurabooks:
    image: jessicamoraes/app-ecomm:1.0
    container_name: ecommerce
    networks:
      - compose-bridge
    ports:
      - 3001:3000

networks:
  compose-bridge:
    driver: bridge